services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 3s
      timeout: 3s
      retries: 20

  seed:
    build: .
    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}
      SEARCH_TABLE: ${SEARCH_TABLE}
      CSV_FILE: ${CSV_FILE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./src/app/data:/src/app/data:ro

    entrypoint: ["sh", "scripts/seed-docker.sh"]
    command: []

    restart: "no"

  app:
    build: .
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}
      SPARQL_ENDPOINT: ${SPARQL_ENDPOINT}

    ports:
      - "3000:3000"

volumes:
  postgres_data:
